server:
  port: 8081
spring:
  application:
    name: course-dubbo-consumer
  dubbo:
    application:
      name: course-dubbo-consumer
    protocol:
      name: dubbo
      port: 20880
    registry:
      address: zookeeper://127.0.0.1:2181